name: DockerImage

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [ 'focal', 'bionic' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Explain why this job ran
        run: echo ${{ github.event_name }} ${{ github.ref }} event triggered this step.
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hannesa2/alexa-auto-${{ matrix.ubuntu }}-4
      - name: Login to DockerHub
        #        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./conan/docker/aac-ubuntu-${{ matrix.ubuntu }}
          #          push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Find Tag
        if: startsWith(github.ref, 'refs/tags/')
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          commit-ish: HEAD
      - name: Create Github release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          hub release create -m "${{steps.tagger.outputs.tag}}" "${{steps.tagger.outputs.tag}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{steps.tagger.outputs.tag}}
